name: 'WeaponMaster'
version: '${project.version}'
main: io.github.greatericontop.weaponmaster.WeaponMasterMain
api-version: 1.17
authors: [greateric, gerseneck, bigfatmidget]
commands:
  weaponmaster:
    description: "WeaponMaster"
    usage: "U: /weaponmaster"
    permission: "weaponmaster.weaponmaster"
    permission-message: "§cYou are not allowed to do this!"
  rpgl:
    description: "[Weapon Master] command for RPG Launcher"
    usage: "U: /rpgl [give]"
    permission: "weaponmaster.rpgl.command"
    permission-message: "§cYou are not allowed to do this!"
  vampaxe:
    description: "[Weapon Master] command for Vampire's Axe"
    usage: "U: /vampaxe [give]"
    permission: "weaponmaster.vampaxe.command"
    permission-message: "§cYou are not allowed to do this!"
  scythe:
    description: "[Weapon Master] command for Death's Scythe"
    usage: "U: /scythe [give]"
    permission: "weaponmaster.deathscythe.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["deathscythe", "deaths-scythe"]
  dragonsword:
    description: "[Weapon Master] command for Dragon Sword"
    usage: "U: /dragonsword [give]"
    permission: "weaponmaster.dragonsword.command"
    permission-message: "§cYou are not allowed to do this!"
  artemis:
    description: "[Weapon Master] command for Artemis"
    usage: "U: /artemis [give]"
    permission: "weaponmaster.artemisbow.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["artemis-bow"]
  anduril:
    description: "[Weapon Master] command for Anduril"
    usage: "U: /anduril [give]"
    permission: "weaponmaster.anduril.command"
    permission-message: "§cYou are not allowed to do this!"
  excalibur:
    description: "[Weapon Master] command for Excalibur"
    usage: "U: /excalibur [give]"
    permission: "weaponmaster.excalibur.command"
    permission-message: "§cYou are not allowed to do this!"
  exodus:
    description: "[Weapon Master] command for Exodus"
    usage: "U: /exodus [give]"
    permission: "weaponmaster.exodus.command"
    permission-message: "§cYou are not allowed to do this!"
  rocketstick:
    description: "[Weapon Master] command for Rocket Stick"
    usage: "U: /rocketstick [give]"
    permission: "weaponmaster.rocketstick.command"
    permission-message: "§cYou are not allowed to do this!"
  helios:
    description: "[Weapon Master] command for Helios"
    usage: "U: /helios [give]"
    permission: "weaponmaster.helios.command"
    permission-message: "§cYou are not allowed to do this!"
  scylla:
    description: "[Weapon Master] command for Scylla's Chestplate"
    usage: "U: /scylla [give]"
    permission: "weaponmaster.scylla.command"
    permission-message: "§cYou are not allowed to do this!"
  hermesboots:
    description: "[Weapon Master] command for Herme's Boots"
    usage: "U: /hermesboots [give]"
    permission: "weaponmaster.hermesboots.command"
    permission-message: "§cYou are not allowed to do this!"
  lifehelmet:
    description: "[Weapon Master] command for Helmet of Life"
    usage: "U: /lifehelmet [give]"
    permission: "weaponmaster.lifehelmet.command"
    permission-message: "§cYou are not allowed to do this!"
  cavemansword:
    description: "[Weapon Master] command for Caveman Sword"
    usage: "U: /cavemansword [give | setStats <level> <exp>]"
    permission: "weaponmaster.cavemansword.command"
    permission-message: "§cYou are not allowed to do this!"
  warlockpants:
    description: "[Weapon Master] command for Warlock Pants"
    usage: "U: /warlockpants [give]"
    permission: "weaponmaster.warlockpants.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["warlock"]
  fireball:
    description: "[Weapon Master] command for Fireball"
    usage: "U: /fireball [give]"
    permission: "weaponmaster.fireball.command"
    permission-message: "§cYou are not allowed to do this!"
  atombomb:
    description: "[Weapon Master] command for Atom Bomb"
    usage: "U: /atombomb [give]"
    permission: "weaponmaster.atombomb.command"
    permission-message: "§cYou are not allowed to do this!"
  netheritestaff:
    description: "[Weapon Master] command for Netherite Staff"
    usage: "U: /netheritestaff [give]"
    permission: "weaponmaster.netheritestaff.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["netherite-st", "staff"]
  sniperrifle:
    description: "[Weapon Master] command for Sniper Rifle"
    usage: "U: /sniperrifle [give]"
    permission: "weaponmaster.sniperrifle.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["sniper", "sniper-rifle"]
  minersblessing:
    description: "[Weapon Master] command for Miner's Blessing"
    usage: "U: /minersblessing [give]"
    permission: "weaponmaster.minersblessing.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["miners-blessing"]
  pilotsword:
    description: "[Weapon Master] command for Pilot's Sword"
    usage: "U: /pilotsword [give]"
    permission: "weaponmaster.minersblessing.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["pilots-sword"]
  shreddedaxe:
    description: "[Weapon Master] command for Shredded Axe"
    usage: "U: /shreddedaxe [give]"
    permission: "weaponmaster.shreddedaxe.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["shredded", "shredded-axe"]
  napalm:
    description: "[Weapon Master] command for Napalm Missile"
    usage: "U: /napalm [give]"
    permission: "weaponmastser.napalm.command"
    permission-message: "§cYou are not allowed to do this!"
  ninjabow:
    description: "[Weapon Master] command for Ninja Bow"
    usage: "U: /ninjabow [give]"
    permission: "weaponmastser.ninjabow.command"
    permission-message: "§cYou are not allowed to do this!"
  minoritem:
    description: "[Weapon Master] command for minor items"
    usage: "U: /minoritem list"
    permission: "weaponmaster.command.minoritem"
    permission-message: "§cYou are not allowed to do this!"
  dragonarmor:
    description: "[Weapon Master] command for Dragon Armor"
    usage: "U: /dragonarmor [give]"
    permission: "weaponmaster.dragonarmor.command"
    permission-message: "§cYou are not allowed to do this!"
  coppersword:
    description: "[Weapon Master] command for Copper Sword"
    usage: "U: /coppersword give"
    permission: "weaponmaster.coppersword.command"
    permission-message: "§cYou are not allowed to do this!"
  poseidontrident:
    description: "[Weapon Master] command for Poseidon's Trident"
    usage: "U: /poseidontrident give"
    permission: "weaponmaster.poseidontrident.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["poseidon", "poseidon-trident"]

permissions:
  weaponmaster.weaponmaster:
    default: true
  #
  weaponmaster.command.minoritem:
    default: op
  #
  weaponmaster.rpgl.command:
    default: op
  weaponmaster.rpgl.use:
    default: true
  #
  weaponmaster.vampaxe.command:
    default: op
  weaponmaster.vampaxe.use:
    default: true
  #
  weaponmaster.deathscythe.command:
    default: op
  weaponmaster.deathscythe.use:
    default: true
  #
  weaponmaster.dragonsword.command:
    default: op
  weaponmaster.dragonsword.use:
    default: true
  #
  weaponmaster.artemisbow.command:
    default: op
  weaponmaster.artemisbow.use:
    default: true
  #
  weaponmaster.anduril.command:
    default: op
  weaponmaster.anduril.use:
    default: true
  #
  weaponmaster.excalibur.command:
    default: op
  weaponmaster.excalibur.use:
    default: true
  #
  weaponmaster.exodus.command:
    default: op
  weaponmaster.exodus.use:
    default: true
  #
  weaponmaster.rocketstick.command:
    default: op
  weaponmaster.rocketstick.use:
    default: true
  #
  weaponmaster.helios.command:
    default: op
  weaponmaster.helios.use:
    default: true
  #
  weaponmaster.scylla.command:
    default: op
  weaponmaster.scylla.use:
    default: true
  #
  weaponmaster.hermesboots.command:
    default: op
  weaponmaster.hermesboots.use:
    default: true
  #
  weaponmaster.lifehelmet.command:
    default: op
  weaponmaster.lifehelmet.use:
    default: true
  #
  weaponmaster.cavemansword.command:
    default: op
  weaponmaster.cavemansword.use:
    default: true
  #
  weaponmaster.warlockpants.command:
    default: op
  weaponmaster.warlockpants.use:
    default: true
  #
  weaponmaster.fireball.command:
    default: op
  weaponmaster.fireball.use:
    default: true
  #
  weaponmaster.atombomb.command:
    default: op
  weaponmaster.atombomb.use:
    default: op
  #
  weaponmaster.netheritestaff.command:
    default: op
  weaponmaster.netheritestaff.use:
    default: true
  #
  weaponmaster.sniperrifle.command:
    default: op
  weaponmaster.sniperrifle.use:
    default: true
  #
  weaponmaster.minersblessing.command:
    default: op
  weaponmaster.minersblessing.use:
    default: true
  #
  weaponmaster.pilotsword.command:
    default: op
  weaponmaster.pilotsword.use:
    default: true
  #
  weaponmaster.shreddedaxe.command:
    default: op
  weaponmaster.shreddedaxe.use:
    default: true
  #
  weaponmaster.napalm.command:
    deafult: op
  weaponmaster.napalm.use:
    default: true
  #
  weaponmaster.ninjabow.command:
    deafult: op
  weaponmaster.ninjabow.use:
    default: true
  #
  weaponmaster.dragonarmor.command:
    deafult: op
  weaponmaster.dragonarmor.use:
    default: true
  #
  weaponmaster.coppersword.command:
    default: op
  weaponmaster.coppersword.use:
    default: true
  #
  weaponmaster.poseidontrident.command:
    default: op
  weaponmaster.poseidontrident.use:
    default: true