name: 'WeaponMaster'
version: '1.0.1'
main: io.github.greatericontop.weaponmaster.WeaponMasterMain
api-version: 1.17
commands:
  weaponmaster:
    description: "WeaponMaster"
    usage: "U: /weaponmaster"
    permission: "weaponmaster.weaponmaster"
    permission-message: "§cYou are not allowed to do this!"
  rpgl:
    description: "[Weapon Master] command for RPG Launcher"
    usage: "U: /rpgl [give]"
    permission: "weaponmaster.rpgl.command"
    permission-message: "§cYou are not allowed to do this!"
  vampaxe:
    description: "[Weapon Master] command for Vampire's Axe"
    usage: "U: /vampaxe [give]"
    permission: "weaponmaster.vampaxe.command"
    permission-message: "§cYou are not allowed to do this!"
  scythe:
    description: "[Weapon Master] command for Death's Scythe"
    usage: "U: /scythe [give]"
    permission: "weaponmaster.deathscythe.command"
    permission-message: "§cYou are not allowed to do this!"
  dragonsword:
    description: "[Weapon Master] command for Dragon Sword"
    usage: "U: /dragonsword [give]"
    permission: "weaponmaster.dragonsword.command"
    permission-message: "§cYou are not allowed to do this!"
  artemis:
    description: "[Weapon Master] command for Artemis"
    usage: "U: /artemis [give]"
    permission: "weaponmaster.artemisbow.command"
    permission-message: "§cYou are not allowed to do this!"
  anduril:
    description: "[Weapon Master] command for Anduril"
    usage: "U: /anduril [give]"
    permission: "weaponmaster.anduril.command"
    permission-message: "§cYou are not allowed to do this!"
  excalibur:
    description: "[Weapon Master] command for Excalibur"
    usage: "U: /excalibur [give]"
    permission: "weaponmaster.excalibur.command"
    permission-message: "§cYou are not allowed to do this!"
  exodus:
    description: "[Weapon Master] command for Exodus"
    usage: "U: /exodus [give]"
    permission: "weaponmaster.exodus.command"
    permission-message: "§cYou are not allowed to do this!"
  assaultrifle:
    description: "[Weapon Master] command for Assault Rifle"
    usage: "U: /assaultrifle [give]"
    permission: "weaponmaster.assaultrifle.command"
    permission-message: "§cYou are not allowed to do this!"
permissions:
  #
  weaponmaster.*:
    description: "All weaponmaster commands"
    default: false
    children:
      weaponmaster.weaponmaster: true
      weaponmaster.rpgl.command: true
      weaponmaster.rpgl.use: true
      weaponmaster.vampaxe.command: true
      weaponmaster.vampaxe.use: true
      weaponmaster.deathscythe.command: true
      weaponmaster.deathscythe.use: true
      weaponmaster.dragonsword.command: true
      weaponmaster.dragonsword.use: true
      weaponmaster.artemis.command: true
      weaponmaster.artemis.use: true
      weaponmaster.anduril.command: true
      weaponmaster.anduril.use: true
      weaponmaster.excalibur.command: true
      weaponmaster.excalibur.use: true
      weaponmaster.exodus.command: true
      weaponmaster.exodus.use: true
      weaponmaster.assaultrifle.command: true
      weaponmaster.assaultrifle.use: true
  weaponmaster.weaponmaster:
    description: "Allows usage of /weaponmaster"
    default: true
  #
  weaponmaster.rpgl.command:
    description: "Allows usage of /rpgl"
    default: op
  weaponmaster.rpgl.use:
    description: "Lets you use the item"
    default: true
  #
  weaponmaster.vampaxe.command:
    description: "Allows usage of /vampaxe"
    default: op
  weaponmaster.vampaxe.use:
    description: "Lets you use the item"
    default: true
  #
  weaponmaster.deathscythe.command:
    description: "Allows usage of /scythe"
    default: op
  weaponmaster.deathscythe.use:
    description: "Lets you use the item"
    default: true
  #
  weaponmaster.dragonsword.command:
    description: "Allows usage of /dragonsword"
    default: op
  weaponmaster.dragonsword.use:
    description: "Lets you use the item"
    default: true
  #
  weaponmaster.artemisbow.command:
    description: "Allows usage of /artemis"
    default: op
  weaponmaster.artemisbow.use:
    description: "Lets you use the item"
    default: true
  #
  weaponmaster.anduril.command:
    description: "Allows usage of /anduril"
    default: op
  weaponmaster.anduril.use:
    description: "Lets you use the item"
    default: true
  #
  weaponmaster.excalibur.command:
    description: "Allows usage of /excalibur"
    default: op
  weaponmaster.excalibur.use:
    description: "Lets you use the item"
    default: true
  #
  weaponmaster.exodus.command:
    description: "Allows usage of /exodus"
    default: op
  weaponmaster.exodus.use:
    description: "Lets you use the item"
    default: true
  #
  weaponmaster.assaultrifle.command:
    description: "Allows usage of /assaultrifle"
    default: op
  weaponmaster.assaultrifle.use:
    description: "Lets you use the item"
    default: true