name: 'WeaponMaster'
version: '${project.version}'
main: io.github.greatericontop.weaponmaster.WeaponMasterMain
api-version: 1.17
authors: [greateric]
commands:
  weaponmaster:
    description: "WeaponMaster"
    usage: "U: /weaponmaster"
    permission: "weaponmaster.weaponmaster"
    permission-message: "§cYou are not allowed to do this!"
  rpgl:
    description: "[Weapon Master] command for RPG Launcher"
    usage: "U: /rpgl [give]"
    permission: "weaponmaster.rpgl.command"
    permission-message: "§cYou are not allowed to do this!"
  vampaxe:
    description: "[Weapon Master] command for Vampire's Axe"
    usage: "U: /vampaxe [give]"
    permission: "weaponmaster.vampaxe.command"
    permission-message: "§cYou are not allowed to do this!"
  scythe:
    description: "[Weapon Master] command for Death's Scythe"
    usage: "U: /scythe [give]"
    permission: "weaponmaster.deathscythe.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["deathscythe", "deaths-scythe"]
  dragonsword:
    description: "[Weapon Master] command for Dragon Sword"
    usage: "U: /dragonsword [give]"
    permission: "weaponmaster.dragonsword.command"
    permission-message: "§cYou are not allowed to do this!"
  artemis:
    description: "[Weapon Master] command for Artemis"
    usage: "U: /artemis [give]"
    permission: "weaponmaster.artemisbow.command"
    permission-message: "§cYou are not allowed to do this!"
  anduril:
    description: "[Weapon Master] command for Anduril"
    usage: "U: /anduril [give]"
    permission: "weaponmaster.anduril.command"
    permission-message: "§cYou are not allowed to do this!"
  excalibur:
    description: "[Weapon Master] command for Excalibur"
    usage: "U: /excalibur [give]"
    permission: "weaponmaster.excalibur.command"
    permission-message: "§cYou are not allowed to do this!"
  exodus:
    description: "[Weapon Master] command for Exodus"
    usage: "U: /exodus [give]"
    permission: "weaponmaster.exodus.command"
    permission-message: "§cYou are not allowed to do this!"
  rocketstick:
    description: "[Weapon Master] command for Rocket Stick"
    usage: "U: /rocketstick [give]"
    permission: "weaponmaster.rocketstick.command"
    permission-message: "§cYou are not allowed to do this!"
  helios:
    description: "[Weapon Master] command for Helios"
    usage: "U: /helios [give]"
    permission: "weaponmaster.helios.command"
    permission-message: "§cYou are not allowed to do this!"
  scylla:
    description: "[Weapon Master] command for Scylla's Chestplate"
    usage: "U: /scylla [give]"
    permission: "weaponmaster.scylla.command"
    permission-message: "§cYou are not allowed to do this!"
  hermesboots:
    description: "[Weapon Master] command for Herme's Boots"
    usage: "U: /hermesboots [give]"
    permission: "weaponmaster.hermesboots.command"
    permission-message: "§cYou are not allowed to do this!"
  lifehelmet:
    description: "[Weapon Master] command for Helmet of Life"
    usage: "U: /lifehelmet [give]"
    permission: "weaponmaster.lifehelmet.command"
    permission-message: "§cYou are not allowed to do this!"
  cavemansword:
    description: "[Weapon Master] command for Caveman Sword"
    usage: "U: /cavemansword [give]"
    permission: "weaponmaster.cavemansword.command"
    permission-message: "§cYou are not allowed to do this!"
  warlockpants:
    description: "[Weapon Master] command for Warlock Pants"
    usage: "U: /warlockpants [give]"
    permission: "weaponmaster.warlockpants.command"
    permission-message: "§cYou are not allowed to do this!"
    aliases: ["warlock"]
  assaultrifle:
    description: "[Weapon Master] command for Assault Rifle"
    usage: "U: /assaultrifle [give]"
    permission: "weaponmaster.assaultrifle.command"
    permission-message: "§cYou are not allowed to do this!"
permissions:
  weaponmaster.weaponmaster:
    default: true
  #
  weaponmaster.rpgl.command:
    default: op
  weaponmaster.rpgl.use:
    default: true
  #
  weaponmaster.vampaxe.command:
    default: op
  weaponmaster.vampaxe.use:
    default: true
  #
  weaponmaster.deathscythe.command:
    default: op
  weaponmaster.deathscythe.use:
    default: true
  #
  weaponmaster.dragonsword.command:
    default: op
  weaponmaster.dragonsword.use:
    default: true
  #
  weaponmaster.artemisbow.command:
    default: op
  weaponmaster.artemisbow.use:
    default: true
  #
  weaponmaster.anduril.command:
    default: op
  weaponmaster.anduril.use:
    default: true
  #
  weaponmaster.excalibur.command:
    default: op
  weaponmaster.excalibur.use:
    default: true
  #
  weaponmaster.exodus.command:
    default: op
  weaponmaster.exodus.use:
    default: true
  #
  weaponmaster.rocketstick.command:
    default: op
  weaponmaster.rocketstick.use:
    default: true
  #
  weaponmaster.helios.command:
    default: op
  weaponmaster.helios.use:
    default: true
  #
  weaponmaster.scylla.command:
    default: op
  weaponmaster.scylla.use:
    default: true
  #
  weaponmaster.hermesboots.command:
    default: op
  weaponmaster.hermesboots.use:
    default: true
  #
  weaponmaster.lifehelmet.command:
    default: op
  weaponmaster.lifehelmet.use:
    default: true
  #
  weaponmaster.cavemansword.command:
    default: op
  weaponmaster.cavemansword.use:
    default: true
  #
  weaponmaster.warlockpants.command:
    default: op
  weaponmaster.warlockpants.use:
    default: true
  #
  weaponmaster.assaultrifle.command:
    default: op
  weaponmaster.assaultrifle.use:
    default: true